<div id='g-kartpay_admin-dashboard-box' class='ai2html'>
	<!-- Generated by ai2html v0.63 - 2017-04-02 - 14:28 -->
	<!-- ai file: kartpay_admin-dashboard -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-kartpay_admin-dashboard-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='1920'>
		<style type='text/css' media='screen,print'>
			#g-kartpay_admin-dashboard-Artboard_1{
				position:relative;
				overflow:hidden;
				width:1920px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-kartpay_admin-dashboard-Artboard_1 p{
				font-family:nyt-franklin,arial,helvetica,sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-kartpay_admin-dashboard-Artboard_1 .g-aiPstyle0 {
				font-size:14px;
				line-height:17px;
				color:#ffffff;
			}
			#g-kartpay_admin-dashboard-Artboard_1 .g-aiPstyle1 {
				font-size:18px;
				line-height:22px;
				color:#ffffff;
			}
			#g-kartpay_admin-dashboard-Artboard_1 .g-aiPstyle2 {
				font-size:18px;
				line-height:22px;
				color:#000000;
			}
			#g-kartpay_admin-dashboard-Artboard_1 .g-aiPstyle3 {
				font-size:20px;
				line-height:24px;
				color:#000000;
			}
			#g-kartpay_admin-dashboard-Artboard_1 .g-aiPstyle4 {
				font-size:18px;
				line-height:22px;
				color:#000000;
			}
			#g-kartpay_admin-dashboard-Artboard_1 .g-aiPstyle5 {
				font-size:18px;
				line-height:22px;
				color:#000000;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-kartpay_admin-dashboard-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='{{ asset("images/kartpay_admin-dashboard-Artboard_1.png") }}'
				/>
			<div id='g-ai0-1' class='g-header g-aiAbs' style='top:1.4815%;left:87.0313%;'>
				<p class='g-aiPstyle0'>3</p>
			</div>
			<div id='g-ai0-2' class='g-header g-aiAbs' style='top:2.5926%;left:93.125%;'>
				<p class='g-aiPstyle1'>Administrator</p>
			</div>
			<div id='g-ai0-3' class='g-menu g-aiAbs' style='top:15.8333%;left:6.7188%;'>
				<p class='g-aiPstyle2'>Welcome,</p>
			</div>
			<div id='g-ai0-4' class='g-menu g-aiAbs' style='top:18.2407%;left:6.7188%;'>
				<p class='g-aiPstyle3'>{{ Auth::user()->name }} (<a href="{{ route('logout') }}"
																			                      onclick="event.preventDefault();
																			                      document.getElementById('logout-form').submit();">LOGOUT
																													</a>)
				</p>
			</div>

			<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
				{{ csrf_field() }}
			</form>

			<div id='g-ai0-5' class='g-menu g-aiAbs' style='top:24.6296%;left:1.0417%;'>
				<p class='g-aiPstyle4'>GENERAL</p>
			</div>
			<div id='g-ai0-6' class='g-menu g-aiAbs' style='top:30.463%;left:2.6823%;'>
				<p class='g-aiPstyle4'>Home</p>
			</div>
			<div id='g-ai0-7' class='g-menu g-aiAbs' style='top:35.1852%;left:2.526%;'>
				<p class='g-aiPstyle5'>Merchant Administration</p>
			</div>
			<div id='g-ai0-8' class='g-menu g-aiAbs' style='top:38.8889%;left:2.526%;'>
				<p class='g-aiPstyle5'>Merchant Transaction</p>
			</div>
			<div id='g-ai0-9' class='g-menu g-aiAbs' style='top:42.5926%;left:2.526%;'>
				<p class='g-aiPstyle5'>Application Settings</p>
			</div>
			<div id='g-ai0-10' class='g-menu g-aiAbs' style='top:47.5%;left:3.5677%;'>
				<p class='g-aiPstyle5'>Sms Settings</p>
			</div>
			<div id='g-ai0-11' class='g-menu g-aiAbs' style='top:51.4815%;left:3.5677%;'>
				<p class='g-aiPstyle5'>Email Settings</p>
			</div>
			<div id='g-ai0-12' class='g-menu g-aiAbs' style='top:55.5556%;left:3.5677%;'>
				<p class='g-aiPstyle5'>Session</p>
			</div>
			<div id='g-ai0-13' class='g-menu g-aiAbs' style='top:59.7222%;left:4.8177%;'>
				<p class='g-aiPstyle5'>Customer Settings</p>
			</div>
			<div id='g-ai0-14' class='g-menu g-aiAbs' style='top:63.8889%;left:4.8177%;'>
				<p class='g-aiPstyle5'>Administrator Settings</p>
			</div>
			<div id='g-ai0-15' class='g-menu g-aiAbs' style='top:67.963%;left:3.5677%;'>
				<p class='g-aiPstyle5'>TDR</p>
			</div>
			<div id='g-ai0-16' class='g-menu g-aiAbs' style='top:73.8889%;left:2.526%;'>
				<p class='g-aiPstyle5'>Accounting</p>
			</div>
			<div id='g-ai0-17' class='g-menu g-aiAbs' style='top:77.5926%;left:2.526%;'>
				<p class='g-aiPstyle5'>Admin User Management</p>
			</div>
		</div>
	</div>

	<!-- End ai2html - 2017-04-02 - 14:28 -->
</div>
