<?php

namespace App\Libraries;

class Banks {

	public static $banks = [
        'Andhra Bank', 
        'Bank of Baharin and Kuwait',
        'Bank of Baroda Corporate',
        'Bank of Baroda Retail',
        'Bank of India',
        'Bank of Maharashtra',
        'Canara Bank',
        'Catholic Syrian Bank',
        'Central Bank of India',
        'Citibank',
        'City Union Bank',
        'Corporation Bank',
        'DBS Bank Ltd',
        'DCB BANK Business',
        'DCB BANK Personal',
        'Deutsche Bank',
        'Dhanlaxmi Bank',
        'Federal Bank',
        'IDBI Bank',
        'Indian Bank',
        'Indian Overseas Bank',
        'IndusInd Bank',
        'ING Vysya Bank',
        'Jammu and kashmir Bank',
        'Karnataka Bank',
        'Karur Vysya Bank',
        'Lakshmi Vilas Bank',
        'Oriental Bank Of Commerce',
        'Punjab National Bank',
        'Punjab National Bank Corporate Accounts',
        'Royal Bank Of Scotland',
        'Saraswat Bank',
        'Shamrao Vithal Co-op. Bank Ltd',
        'South Indian Bank',
        'Standard Chartered Bank',
        'State Bank Of Bikaner and Jaipur',
        'State Bank Of Hyderabad',
        'State Bank Of Mysore',
        'State Bank of Patiala',
        'State Bank of Travancore',
        'Syndicate Bank',
        'Tamilnad Mercantile Bank',
        'Union Bank of India',
        'United Bank of India',
        'Vijaya Bank',
        'YES Bank',
        'Axis Bank',
        'State Bank of India',
        'Kotak Mahindra Bank',
        'HDFC Bank',
        'ICICI Bank'
	];
}